# GoFrame Configuration
server:
  address: ":8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  default:
    link: ${GO_PATH}
    debug: true

logger:
  level: "all"
  stdout: true