// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package posts

import (
	v1 "gfbackend/internal/controller/posts/v1"
)

type (
	Controller struct{}
)

var (
	ControllerV1 = v1.ControllerV1{}
)

func New() *Controller {
	return &Controller{}
}