// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfbackend/internal/dao/internal"
)

// chatConversationsDao is the data access object for the table chat_conversations.
// You can define custom methods on it to extend its functionality as needed.
type chatConversationsDao struct {
	*internal.ChatConversationsDao
}

var (
	// ChatConversations is a globally accessible object for table chat_conversations operations.
	ChatConversations = chatConversationsDao{internal.NewChatConversationsDao()}
)

// Add your custom methods and functionality below.
