// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfbackend/internal/dao/internal"
)

// chatMessagesDao is the data access object for the table chat_messages.
// You can define custom methods on it to extend its functionality as needed.
type chatMessagesDao struct {
	*internal.ChatMessagesDao
}

var (
	// ChatMessages is a globally accessible object for table chat_messages operations.
	ChatMessages = chatMessagesDao{internal.NewChatMessagesDao()}
)

// Add your custom methods and functionality below.
