// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfbackend/internal/dao/internal"
)

// likesDao is the data access object for the table likes.
// You can define custom methods on it to extend its functionality as needed.
type likesDao struct {
	*internal.LikesDao
}

var (
	// Likes is a globally accessible object for table likes operations.
	Likes = likesDao{internal.NewLikesDao()}
)

// Add your custom methods and functionality below.
