// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfbackend/internal/dao/internal"
)

// postsToTagsDao is the data access object for the table posts_to_tags.
// You can define custom methods on it to extend its functionality as needed.
type postsToTagsDao struct {
	*internal.PostsToTagsDao
}

var (
	// PostsToTags is a globally accessible object for table posts_to_tags operations.
	PostsToTags = postsToTagsDao{internal.NewPostsToTagsDao()}
)

// Add your custom methods and functionality below.
