// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfbackend/internal/dao/internal"
)

// postCommentsDao is the data access object for the table post_comments.
// You can define custom methods on it to extend its functionality as needed.
type postCommentsDao struct {
	*internal.PostCommentsDao
}

var (
	// PostComments is a globally accessible object for table post_comments operations.
	PostComments = postCommentsDao{internal.NewPostCommentsDao()}
)

// Add your custom methods and functionality below.
