// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfbackend/internal/dao/internal"
)

// profilesDao is the data access object for the table profiles.
// You can define custom methods on it to extend its functionality as needed.
type profilesDao struct {
	*internal.ProfilesDao
}

var (
	// Profiles is a globally accessible object for table profiles operations.
	Profiles = profilesDao{internal.NewProfilesDao()}
)

// Add your custom methods and functionality below.
