// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfbackend/internal/dao/internal"
)

// workspacesDao is the data access object for the table workspaces.
// You can define custom methods on it to extend its functionality as needed.
type workspacesDao struct {
	*internal.WorkspacesDao
}

var (
	// Workspaces is a globally accessible object for table workspaces operations.
	Workspaces = workspacesDao{internal.NewWorkspacesDao()}
)

// Add your custom methods and functionality below.
